// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7yZfdBnXDGeMctYPeZdPpltUTGU6BWwM',
    appId: '1:448376363466:web:349e4f20f67e3afb479733',
    messagingSenderId: '448376363466',
    projectId: 'aitherapist-51dbc',
    authDomain: 'aitherapist-51dbc.firebaseapp.com',
    storageBucket: 'aitherapist-51dbc.appspot.com',
    measurementId: 'G-NXQEYNNDZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28xpfoynJDeUdNiP1qIddQVi_Saw6ais',
    appId: '1:448376363466:android:69fadfd8d6786aec479733',
    messagingSenderId: '448376363466',
    projectId: 'aitherapist-51dbc',
    storageBucket: 'aitherapist-51dbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk60x6PQIoAw4hi0hgJzRHaIYz9lSoiVg',
    appId: '1:448376363466:ios:338a50bf15f412a2479733',
    messagingSenderId: '448376363466',
    projectId: 'aitherapist-51dbc',
    storageBucket: 'aitherapist-51dbc.appspot.com',
    iosBundleId: 'com.example.aitherapist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk60x6PQIoAw4hi0hgJzRHaIYz9lSoiVg',
    appId: '1:448376363466:ios:3c967f99120f0612479733',
    messagingSenderId: '448376363466',
    projectId: 'aitherapist-51dbc',
    storageBucket: 'aitherapist-51dbc.appspot.com',
    iosBundleId: 'com.example.aitherapist.RunnerTests',
  );
}
